apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  label:
    app: nginx
  annotations:
    annotation-key1: annotation-value1
    description: ini adalah aplikasi nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80